name: Split PT Tracker List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write  # 允许写入代码
  
jobs:
  split-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download tracker list
        run: |
          curl -o trackers_all.txt "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt"

      - name: Run split script
        run: |
          chmod +x scripts/split_tracker.sh
          ./scripts/split_tracker.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add trackers_all.txt output/pt_tracker_domain.txt output/pt_tracker_ip.txt
          git commit -m "Update tracker list and split results - $(date +'%Y-%m-%d')"
          git push
