name: Split Tracker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  split-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download tracker list
        run: |
          curl -o trackers_all.txt "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt"
          echo "Downloaded trackers_all.txt"
          ls -la
          head -n 10 trackers_all.txt  # 显示前10行确认内容

      - name: Run split script
        run: |
          chmod +x scripts/split_tracker.sh
          ./scripts/split_tracker.sh
          ls -la output/  # 确认输出文件

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add trackers_all.txt output/pt_tracker_domain.txt output/pt_tracker_ip.txt
          git commit -m "Update split tracker results - $(date +'%Y-%m-%d')"
          git push
