name: Split Tracker List

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  split-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download tracker list
        run: |
          curl -o trackers_all.txt "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt"
          echo "Downloaded trackers_all.txt"
          ls -la
          head -n 10 trackers_all.txt || echo "trackers_all.txt is empty"

      - name: Run split script
        run: |
          chmod +x scripts/split_tracker.sh
          ./scripts/split_tracker.sh
          ls -la output/ || echo "No output directory created"
          cat output/pt_tracker_domain.txt || echo "Domain file not created"
          cat output/pt_tracker_ip.txt || echo "IP file not created"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add trackers_all.txt output/pt_tracker_domain.txt output/pt_tracker_ip.txt
          git commit -m "Update trackers_all.txt and split results - $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push || echo "Push failed"
